In [3]:
# Decision Tree:
# Makes predictions using a series of if/else decisions.
# Gini impurity is used to choose the best splits.

import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [4]:
# Load dataset
data = load_breast_cancer()


In [5]:
X = data.data
y = data.target

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Classes:", data.target_names)

X shape: (569, 30)
y shape: (569,)
Classes: ['malignant' 'benign']


In [6]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])


Training samples: 455
Testing samples: 114


In [13]:
# Create Decision Tree
l= [2 , 5 ,None]
for i in l:
  model = DecisionTreeClassifier(
    max_depth=i,
    criterion="gini",
    random_state=42
  )

   # Train model
  model.fit(X_train, y_train)


  # Make predictions
  y_pred = model.predict(X_test)

  # Evaluate model
  print("\nAccuracy:", accuracy_score(y_test, y_pred))

  print("\nConfusion Matrix:")
  print(confusion_matrix(y_test, y_pred))

  print("\nClassification Report:")
  print(classification_report(y_test, y_pred))


Accuracy: 0.9298245614035088

Confusion Matrix:
[[37  6]
 [ 2 69]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.86      0.90        43
           1       0.92      0.97      0.95        71

    accuracy                           0.93       114
   macro avg       0.93      0.92      0.92       114
weighted avg       0.93      0.93      0.93       114


Accuracy: 0.9473684210526315

Confusion Matrix:
[[40  3]
 [ 3 68]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114


Accuracy: 0.9473684210526315

Confusion Matrix:
[[40  3]
 [ 3 68]]

Classification Report:
              precision    recall  f1-score   support

           0   

In [14]:
for depth in [2, 5, None]:
    model = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    model.fit(X_train, y_train)

    train_accuracy = accuracy_score(
        y_train,
        model.predict(X_train)
    )

    test_accuracy = accuracy_score(
        y_test,
        model.predict(X_test)
    )

    print("max_depth:", depth)
    print("Train Accuracy:", train_accuracy)
    print("Test Accuracy:", test_accuracy)
    print()

max_depth: 2
Train Accuracy: 0.9296703296703297
Test Accuracy: 0.9298245614035088

max_depth: 5
Train Accuracy: 0.9956043956043956
Test Accuracy: 0.9473684210526315

max_depth: None
Train Accuracy: 1.0
Test Accuracy: 0.9473684210526315

