In [2]:
# Decision Tree:
# Makes predictions using a series of if/else decisions.
# Gini impurity is used to choose the best splits.

import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [3]:
# Load dataset
data = load_breast_cancer()


In [4]:
X = data.data
y = data.target

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Classes:", data.target_names)

X shape: (569, 30)
y shape: (569,)
Classes: ['malignant' 'benign']


In [5]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])


Training samples: 455
Testing samples: 114


In [7]:
# Create Decision Tree
l= [2 , 5 ,None]
for i in l:
  model = DecisionTreeClassifier(
    max_depth=i,
    criterion="gini",
    random_state=42
  )

   # Train model
  model.fit(X_train, y_train)


  # Make predictions
  y_pred = model.predict(X_test)

  # Evaluate model
  print("\nAccuracy:", accuracy_score(y_test, y_pred))

  print("\nConfusion Matrix:")
  print(confusion_matrix(y_test, y_pred))

  print("\nClassification Report:")
  print(classification_report(y_test, y_pred))


Accuracy: 0.9298245614035088

Confusion Matrix:
[[37  6]
 [ 2 69]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.86      0.90        43
           1       0.92      0.97      0.95        71

    accuracy                           0.93       114
   macro avg       0.93      0.92      0.92       114
weighted avg       0.93      0.93      0.93       114


Accuracy: 0.9473684210526315

Confusion Matrix:
[[40  3]
 [ 3 68]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114


Accuracy: 0.9473684210526315

Confusion Matrix:
[[40  3]
 [ 3 68]]

Classification Report:
              precision    recall  f1-score   support

           0   

In [8]:
for depth in [2, 5, None]:
    model = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    model.fit(X_train, y_train)

    train_accuracy = accuracy_score(
        y_train,
        model.predict(X_train)
    )

    test_accuracy = accuracy_score(
        y_test,
        model.predict(X_test)
    )

    print("max_depth:", depth)
    print("Train Accuracy:", train_accuracy)
    print("Test Accuracy:", test_accuracy)
    print()

max_depth: 2
Train Accuracy: 0.9296703296703297
Test Accuracy: 0.9298245614035088

max_depth: 5
Train Accuracy: 0.9956043956043956
Test Accuracy: 0.9473684210526315

max_depth: None
Train Accuracy: 1.0
Test Accuracy: 0.9473684210526315



In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

DecisionTreeClassifier(
    max_depth=10,
    random_state=42
)
model.fit(X_train, y_train)

train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

train_accuracy = accuracy_score(y_train, train_pred)
test_accuracy = accuracy_score(y_test, test_pred)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

Train Accuracy: 1.0
Test Accuracy: 0.9473684210526315


In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

for depth in [3, 5, 10, None]:

    model = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    model.fit(X_train, y_train)

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_acc = accuracy_score(y_train, train_pred)
    test_acc = accuracy_score(y_test, test_pred)

    print(
        f"max_depth={depth} | "
        f"Train Accuracy={train_acc:.4f} | "
        f"Test Accuracy={test_acc:.4f}"
    )

max_depth=3 | Train Accuracy=0.9780 | Test Accuracy=0.9474
max_depth=5 | Train Accuracy=0.9956 | Test Accuracy=0.9474
max_depth=10 | Train Accuracy=1.0000 | Test Accuracy=0.9474
max_depth=None | Train Accuracy=1.0000 | Test Accuracy=0.9474


In [17]:
param_grid = {
    "criterion": ["gini", "entropy"],
    "max_depth": [3, 5, 10, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5]
}

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dt = DecisionTreeClassifier(random_state=42)

grid_search = GridSearchCV(
    estimator=dt,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:", grid_search.best_score_)

Best Parameters: {'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 10}
Best CV Score: 0.9472527472527472


In [19]:
best_dt = grid_search.best_estimator_

y_pred = best_dt.predict(X_test)

print("Final Test Accuracy:",
      accuracy_score(y_test, y_pred))

Final Test Accuracy: 0.956140350877193
